#!/bin/bash


# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       0
berryc top_gap            0

# Set decoration colors
berryc focus_color         000000
berryc unfocus_color       000000
berryc inner_focus_color   000000
berryc inner_unfocus_color 000000
berryc text_focus_color    000000
berryc text_unfocus_color  000000

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "false"
berryc set_font    "Dina-9"

sxhkd -c /home/ethan/.config/berry/sxhkdrc &
picom --experimental-backends &
gnome-panel &
nitrogen --restore &
pasystray &
nm-applet &
xfce4-clipman &
polkit-dumb-agent &
dunst &
