#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/bin/./screenlayout.sh &
nitrogen --restore &
picom --experimental-backend &
killall polybar
polybar status &
polybar status-mon2 &
mpd --kill
mpd & 
/usr/bin/polkit-dumb-agent &


bspc monitor HDMI-0 -d 1 2 3 4
bspc monitor DP-3 -d  7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config bottom_padding       0
bsp-layout set tall -- --master-size 0.55
#bsp-layout set tall

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop=^6 follow=on
bspc rule -a discord desktop=^7

lxappearance
